[package]

name = "ray-casting"
version = "0.1.0"
authors = [
    "sharpiro <dsharpbb09@gmail.com>",
]

[[bin]]
name = "ray-casting"

[dependencies]
piston = "0.49.0"
piston2d-graphics = "0.35.0"
pistoncore-glutin_window = "0.63.0"
piston2d-opengl_graphics = "0.69.0"
